### PR TITLE
Old laravel compatibility

### PR DESCRIPTION
**Pull request by itsgoingd**
This PR adds compatibility with Laravel versions down to Laravel 5.1.

I broke down the PR into a separate commit for each Laravel version so you can see how much uglier the code gets with each version. 🙃

### CODE REVIEW

**Comment by stefanzweifel** [comment]
Thanks for your contribution!
I will review it over the next days and will come back to you.

At a glance, it seems it adds **a lot of noise** to the project and would make further development much more complicated 🙃 

I'm still considering going the "spatie-way" and only support the latest Laravel version. Since 5.0 the upgrade process is much easier and with tools like Laravel Shift you can also to automate the upgrade.

@jerguslejko What do you think?

**Comment by itsgoingd** [comment]
Honestly, I’d go with 5.5 only support as well, esp. since it’s LTS there is no reason to use older version anymore. But it was kinda fun to write in a weird way. 😁

**Comment by jerguslejko** [comment]
Well, this would definitely make the further development a bit quirky. Mainly testing.

Plus, now that I think about it, if someone wants to see the stats of their project, they are probably still doing an active development on that project. That _might_ suggest that they are running `v5.5`.

So, my opinion: `v5.5` fine with me ¯\_(ツ)_/¯

**Comment by stefanzweifel** [comment]
Then it's settled. The package will only support 5.5 and higher.
Thanks anyway for the PR. It was fun reading through your changes.

**Pull request closed without merging**
