### PR TITLE
Introduce Classifiers

### PR DESCRIPTION
**Pull request by jerguslejko**
This PR replaces "ComponentConfiguration" approach for detecting classes discovered in the application.

The core concept is that every class will run through a list of "classifiers". Each classifier performs a set of checks to determine wether it satisfies the given class (`ModelClassifier` checks wether the given class extends `Illuminate\Database\Eloquent\Model` etc).

This allows us to isolate checks required to indentify a component. `MiddlewareClassifier` is a nice example. To classify a middleware, we need to perform multiple checks (check HttpKernel, check local and global middlewares). By using this approach, logic to indentify a middleware is isolated in the `MiddlewareClassifier` class.

🌵

### CODE REVIEW

**Comment by stefanzweifel** [comment]
That's exactly what I had in mind to do. Thanks! 👍

**Comment by stefanzweifel** [comment]
This structure would also make it much easier to disable/enable certain Classifiers in the config file. For example, if you don't care about Migrations you could remove the Classifier from the config

**Comment by jerguslejko** [comment]
With regards to `MigrationClassifier` as you can see, I have manually marked the test as skipped because I couldn't figure out a way to properly test it.

Well, is it even a good idea to see stats on migrations? It does not seems to be useful getting the number of lines in migrations. Since it does not correlate to the table size, neither is code which is run during the application lifecycle.

I'd suggest removing this functionality.

**Comment by stefanzweifel** [comment]
The LoC count of Migrations and Seeders are not really interesting. I will keep it for now.

Maybe we can hide Migrations and Seeders behind a config option in the future or add a "verbosity" option. 

```
artisan stats -vvv # would show a very detailed report of all components and all found classes
```

**Comment by jerguslejko** [comment]
I would avoid backing off of the verbosity flag. Something line `--include-migrations` or `-m` would me better

**Pull request merged**
