### PR TITLE
Right align and number format

### PR DESCRIPTION
**Pull request by cwt137**
The numbers are not aligned. This patch formats numbers and aligns them.

### CODE REVIEW

**Comment by stefanzweifel** [comment]
Thanks for your PR. Could you check the [Failing Tests](https://travis-ci.org/stefanzweifel/laravel-stats/builds/289800530?utm_source=github_status&utm_medium=notification) and fix them.

[StyleCI](https://styleci.io/analyses/qr0yDD) also nags about the double quotes.

Happy to merge this if these tests pass.

**Comment by jerguslejko** [comment]
Using `number_format()` on `methods`, `classes`, `lines` and `LoC` does not make sense. These numbers will always be an integer value.

Also, using `round` with `number_format` is redundant.

**Comment by stefanzweifel** [comment]
`number_format` also has a thousands separator (eg. `1,000`), but I think we should just leave it like it his.

Numbers and their formatting is always a delicate issue (In Switzerland for example we would format thousands like so `1'000`) and as this output is only viewed by developers I think it doesn't matter.

The right-alignment of the numbers however could make it to `master`.

**Comment by stefanzweifel** [comment]
I've added right alignment of the stats numbers in 3553409e193e19930d1acef43ccf6ce6c2f4fb43.
Thanks for your contribution!

**Pull request closed without merging**
