### PR TITLE
Add Observer Classifier

### PR DESCRIPTION
**Pull request by stefanrempe**
As already mentioned in issue #128 it is not easy to detect the Observers. 

So this PR adds a really simple approach to detect those Observers. I just look if the passed Class implements one of the default observable events. These observable events are also configurable in the laravel-stats config file. 

I think this approach could lead to false positives. 

Maybe another approach would be to detect the calls to `EloquentModel::observe` in the ServiceProvider classes. 

Happy to hear your feedback on this approach.

### CODE REVIEW

**Comment by stefanzweifel** [comment]
Hi Stefan,

Thanks for your PR!

As you mentioned, the approach of matching method names against an array of defined event-names could lead to false positives. 🤔 

> Maybe another approach would be to detect the calls to `EloquentModel::observe` in the ServiceProvider classes.

I would say, that this would be the most "stable" approach for detecting the Observers. However, hooking into the [`observe`](https://github.com/laravel/framework/blob/ea0c86f234138c41441d202e88e43feaff3916e0/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php#L29-L44)-method could be tricky. Do you have any ideas/plans how that could work?

Will have a more in depth look during the next few days.

**Comment by stefanrempe** [comment]
Hey Stefan, 

I thought a little bit about how the approach with hooking into the `observe`-method could be done. The only real idea I came up with is get the source of the `boot`-method from the ServiceProvider and look if the are calls to `observe`. 

This is not 100% accurate detection and there could be false positives. But I think this approach is a little bit better then the approach with looking for the observable events.

**Comment by stefanzweifel** [comment]
Yeah it's definitely not easy to detect them.

Perhabs we have to use some `ReflectionClass`-magic for this Classifier. The `EventListenerClassifier` uses reflection to get to properties which are usually set to private/protected. See:

https://github.com/stefanzweifel/laravel-stats/blob/c68079154626f6858b62c506c3c6a17b85a19fa5/src/Classifiers/EventListenerClassifier.php#L32-L47

To be honest, I haven't used Observers that much and therefore never looked into how they work behind the scenes.


Another idea I had floating in my head: The logic to register Observers is in the `HasEvents`-trait which is used in Eloquent models. So maybe we would have to collect all the Models in the application and grab the registered Observers somehow?
Definitely have to dig deeper into the feature. 😂

**Comment by stefanzweifel** [comment]
Closing this, as it could lead to false positives.
Thanks again for the PR and the notes. Will try to hook into the mentioned `observe`-method in the future.

**Pull request closed without merging**
